[project]
name = "taskiq-aio-kafka"
description = "Kafka broker for taskiq"
authors = [
    {name = "Taskiq team", email = "taskiq@no-reply.com"}
]
maintainers = [
    {name = "Taskiq team", email = "taskiq@no-reply.com"}
]
dynamic = ["version"]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Typing :: Typed",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: System :: Networking",
    "Development Status :: 3 - Alpha",
]
homepage = "https://github.com/taskiq-python/taskiq-aio-kafka"
repository = "https://github.com/taskiq-python/taskiq-aio-kafka"
keywords = ["taskiq", "tasks", "distributed", "async", "kafka", "aiokafka"]
requires-python = ">=3.10,<4"
dependencies = [
    "taskiq>=0.11.20,<1",
    "aiokafka>=0.10.0",
    "kafka-python>=2.0.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    # lint
    "ruff>=0.14.5",
    "black>=25.11.0",
    # type check
    "mypy>=1.18.2",
    # tests
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "coverage>=7.11.3",
    "pytest-xdist[psutil]>=3.8.0",
    "anyio>=4.11.0",
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.hatch.build.targets.wheel]
packages = ["taskiq_aio_kafka"]

[tool.pytest.ini_options]
log_level = 'INFO'
anyio_mode = "auto"

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false
warn_unused_ignores = false

[tool.ruff]
target-version="py310"
lint.select = [
    "ALL",
]
lint.ignore = [
    "ANN401",  # Missing type annotation
    "D100",    # Missing docstring in public module
    "D401",    # First line should be in imperative mood
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "EM101",   # Exception must not use a string literal, assign to variable first
    "TRY003",  # Avoid specifying long messages outside the exception class
]

lint.mccabe = { max-complexity = 10 }
exclude = [".venv/"]
line-length = 88

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",    # Use of assert detected
    "SLF001",  # Private member accessed
    "RET503",  # Missing explicit `return`
    "INP001",  # Part of an implicit namespace package
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
ignore-decorators = ["typing.overload"]
