name: Testing package

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  lint:
    strategy:
      matrix:
        cmd: ["black", "ruff", "mypy"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: 3.11
          version: "latest"
          python-version: 3.11
      - name: Install deps
        run: uv sync --all-extras
      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    services:
      kafka:
        image: apache/kafka:4.1.1
        ports:
          - 9092:9092
        options: >-
          --health-cmd "nc -z localhost 9092"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 8
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.py_version }}
          version: "latest"
          python-version: ${{ matrix.py_version }}
      - name: Install deps
        run: uv sync --all-extras
      - name: Run pytest check
        run: uv run pytest -vv -n auto --cov="taskiq_aio_kafka" .
      - name: Generate report
        run: uv run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest' && matrix.py_version == '3.10'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
